# Generated by Django 5.2.15 on 2026-08-30 11:29

import django.db.models.deletion
from django.db import migrations, models


def migrate_product_gallery(apps, schema_editor):
    """
    Convert the old ProductGallery records into the new
    Product + ProductImage structure.
    """

    ProductGallery = apps.get_model(
        "shop",
        "ProductGallery"
    )

    Product = apps.get_model(
        "shop",
        "Product"
    )

    ProductCategory = apps.get_model(
        "shop",
        "ProductCategory"
    )

    ProductImage = apps.get_model(
        "shop",
        "ProductImage"
    )

    # Create a temporary category for existing products.
    # The client can reorganize these later.
    category, created = ProductCategory.objects.get_or_create(
        name="Uncategorized"
    )

    # Keep track of products we've already created.
    products = {}

    for old_product in ProductGallery.objects.all():

        # Create one Product for each unique title.
        if old_product.title not in products:

            product = Product.objects.create(
                title=old_product.title,
                category=category,
                description=""
            )

            products[old_product.title] = product

        else:
            product = products[old_product.title]

        # Attach the old image to the new product.
        ProductImage.objects.create(
            product=product,
            image=old_product.image.name
        )


def reverse_migrate_product_gallery(apps, schema_editor):
    """
    Reverse migration.

    Re-create ProductGallery records from the new
    Product + ProductImage structure.
    """

    ProductGallery = apps.get_model(
        "shop",
        "ProductGallery"
    )

    Product = apps.get_model(
        "shop",
        "Product"
    )

    ProductImage = apps.get_model(
        "shop",
        "ProductImage"
    )

    for product in Product.objects.all():

        for image in ProductImage.objects.filter(
            product=product
        ):

            ProductGallery.objects.create(
                title=product.title,
                image=image.image.name
            )


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_faq"),
    ]

    operations = [

        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True
                    ),
                ),
            ],
        ),

        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True
                    ),
                ),
            ],
        ),

        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="gallery/"
                    ),
                ),
            ],
        ),

        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="shop.productcategory",
            ),
        ),

        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="shop.product",
            ),
        ),

        migrations.RunPython(
            migrate_product_gallery,
            reverse_migrate_product_gallery,
        ),

        migrations.DeleteModel(
            name="ProductGallery",
        ),
    ]
