# Generated by Django 5.2.15 on 2026-08-31 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_productcategory_productimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='shop.product'),
        ),
    ]
